---
title: "Acerca de HAPST"
description: |
  Herramientas para Análisis y Pronóstico de Series de Tiempo en R
author:
  - name: Bastián Aballay L.
    url: https://www.linkedin.com/in/bastianaballay/
date: "`r Sys.Date()`"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Curso diseñado por [Bastián Aballay Leiva](https://www.linkedin.com/in/bastianaballay/) en colaboración con [Estación Lastarria](https://estacionlastarria.cl/). El contenido de esta página web
es en general una traducción al español de parte de los recursos propuestos, con 
algunas apreciaciones y comentarios del autor. HAPST puede pensarse como una 
curatoría de recursos relacionados al análisis y pronośtico de  serie de tiempo utilizando `R`.
El autor garantiza que se ha maximizado el esfuerzo para que cada recurso figure
adecuadamente citado y presente los créditos respectivos a cada autor original. 
En caso contrario, no dude en escribir a `bastian.aballayleiva@gmail.com`.

* Página web [https://estacionlastarria.cl/herramientas-para-analisis-y-pronostico-de-series-de-tiempo-en-r/](https://estacionlastarria.cl/herramientas-para-analisis-y-pronostico-de-series-de-tiempo-en-r/)

# Cronograma Versión 3

|   Actividad   |      Fecha                          |
| ------------- | ----------------------------------- |
| ~~Clase 1~~   | ~~Lunes 11 de Abril de 2022~~   |
| ~~Clase 2~~   | ~~Miércoles 13 de Abril de 2022~~       |
| ~~Clase 3~~   | ~~Lunes 18 de Abril de 2022~~   |
| ~~Clase 4~~   | ~~Miércoles 20 de Abril de 2022~~       |
| ~~Clase 5~~   | ~~Lunes 25 de Enero de 2022~~   |
|   Clase 6     |   Miércoles 27 de Enero de 2022        |

# Cronograma Versión 2

|   Actividad   |      Fecha                          |
| ------------- | ----------------------------------- |
| ~~Clase 1~~   | ~~Miércoles 12 de Enero de 2022~~   |
| ~~Clase 2~~   | ~~Lunes 17 de Enero de 2022~~       |
| ~~Clase 3~~   | ~~Miércoles 19 de Enero de 2022~~   |
| ~~Clase 4~~   | ~~Lunes 24 de Enero de 2022~~       |
| ~~Clase 5~~   | ~~Miércoles 26 de Enero de 2022~~   |
| ~~Clase 6~~   | ~~Lunes 31 de Enero de 2022~~       |

# Cronograma Versión 1

|   Actividad   |      Fecha                          |
| ------------- | ----------------------------------- |
| ~~Clase 1~~   | ~~Lunes 18 de Octubre de 2021~~     |
| ~~Clase 2~~   | ~~Lunes 25 de Octubre de 2021~~     |
| ~~Clase 3~~   | ~~Lunes 08 de Noviembre de 2021~~   |
| ~~Clase 4~~   | ~~Lunes 15 de Noviembre de 2021~~   |
| ~~Clase 5~~   | ~~Lunes 22 de Noviembre de 2021~~   |