---
title: "Clase 1"
description: |
  Introducción al análisis y pronóstico de Series de Tiempo
author:
  - name: Bastián Aballay L.
    url: https://www.linkedin.com/in/bastianaballay/
date: "`r Sys.Date()`"
bibliography: clase-01.bib
output:
  distill::distill_article:
    toc: true
    toc_depth: 2
    code_folding: true
    highlight: kate
    self_contained: false
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Introducción

Una *serie de tiempo* es una colección de observaciones llevadas a cabo de manera
secuencial en el tiempo [@Chatfield2019-jt]. 

<aside>
Series de Tiempo
</aside>

El *análisis de series de tiempo* corresponde al arte de obtener conocimiento
significativo a partir de series de tiempo mediante la exploración de su estructura y características, así como también la identificación
de patrones que puedan ser utilizados para *pronosticar* futuros eventos de ellas.

<aside>
Análisis de Series de Tiempo
</aside>



| Campo                | Serie de Tiempo (Ej.)                                 |
| -------------------- | ----------------------------------------------------- |
| Economía             | Gross Domestic Product (GPD)^[https://fred.stlouisfed.org/]                          |
| Finanzas             | Índices Bursátiles                                    |
| Energía              | Demanda/Consumo Eléctrico                             |
| Ciencia Actuarial    | Mortalidad y Tablas de Vida^[https://en.wikipedia.org/wiki/Lee%E2%80%93Carter_model]                         |
| Retail               | Venta según SKU                                       |
| Comunicaciones       | Tráfico, Procesos binarios                            |
| Química              | Viscosidad de procesos                                |
| Medioambiente        | Temperatura ambiental                                 |
| Operaciones          | Planificación de la producción                        |
| Entretenimiento      | Tickets / Entradas a eventos                          |
| Meteorología         | Lluvia                                                |


# Series de Tiempo

# Forecasting

# Estado del arte

## Competencias de Forecasting

* [A brief history of time series forecasting competitions](https://robjhyndman.com/hyndsight/forecasting-competitions/) por [Rob J. Hyndman](https://robjhyndman.com/)

* 1982 - Actualidad [Makridakis Competitions (M-Competitions) ](https://en.wikipedia.org/wiki/Makridakis_Competitions)

  * 2018 [M4 Forecasting Competition](ttps://forecasters.org/blog/2017/11/10/m4-forecasting-competition/)
  
  * 2020 [M5 Forecasting - Accuracy](https://www.kaggle.com/c/m5-forecasting-accuracy/)

* 2014 [Walmart Recruiting - Store Sales Forecasting](https://www.kaggle.com/c/walmart-recruiting-store-sales-forecasting)

* 2018 [Wikipedia Web Traffic Time Series Forecasting](https://www.kaggle.com/c/web-traffic-time-series-forecasting/)
  

## Journals

* [International Journal of Forecasting](https://forecasters.org/ijf/)

# Forecasting en un contexto de negocios

# Forecasting y Machine Learning

# Un primer intento


